# DQN - ConnectX
params:
  n_epochs: 1000
  steps_per_epoch: 400
  start_steps: 10000
  update_after: 400
  # update_every: 50

  gamma: 0.99
  tau: 0.995
  eps_start: 1.
  eps_decay: 100
  eps_end: 0.05
  lr: 0.0001
  steps_target_update: 500
  replay_size: 1000000
  batch_size: 128

  n_hidden_layers: 2
  n_neurons: 64
  batch_norm: True

  change_terminal_rew: False
  # q_layers: (256, 256)
  # batch_norm: True
